# Generated by Django 4.1.9 on 2023-08-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_marketing", "0011_coursedetailwhatyoulearnitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursedetail",
            name="course_author",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="coursedetail",
            name="course_author_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coursedetail",
            name="course_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
