# Generated by Django 4.1.9 on 2023-08-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_marketing", "0012_coursedetail_course_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursedetail",
            name="course_author_image",
            field=models.ImageField(blank=True, null=True, upload_to="course_author"),
        ),
        migrations.AddField(
            model_name="coursedetail",
            name="course_author_image_alt_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="coursedetail",
            name="course_author_image_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="coursedetail",
            name="course_image",
            field=models.ImageField(blank=True, null=True, upload_to="course_detail"),
        ),
        migrations.AddField(
            model_name="coursedetail",
            name="course_image_alt_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="coursedetail",
            name="course_image_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
