# Generated by Django 4.1.9 on 2023-08-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_marketing", "0013_coursedetail_course_author_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursedetail",
            name="short_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
