# Generated by Django 4.1.9 on 2023-08-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_marketing", "0014_coursedetail_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursedetail",
            name="duration",
            field=models.PositiveIntegerField(
                blank=True, help_text="Enter the duration of the course in hours.", null=True
            ),
        ),
        migrations.AddField(
            model_name="coursedetail",
            name="price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
