# Generated by Django 4.1.9 on 2023-08-28 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("content_marketing", "0016_remove_coursedetailcontent_course_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseOverviewItem",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("course_author", models.CharField(max_length=255)),
                (
                    "link",
                    models.CharField(
                        help_text="Enter link to the course detail page for the specific course", max_length=255
                    ),
                ),
                ("link_title", models.CharField(max_length=255)),
                ("price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True, help_text="Enter the duration of the course in hours.", null=True
                    ),
                ),
                ("course_image", models.ImageField(blank=True, null=True, upload_to="course_overview")),
                ("course_image_title", models.CharField(blank=True, max_length=255, null=True)),
                ("course_image_alt_text", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="CourseOverviewModul",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
    ]
