# Generated by Django 4.1.9 on 2023-08-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_marketing", "0017_courseoverviewitem_courseoverviewmodul"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseoverviewitem",
            name="link_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
