# Generated by Django 4.1.9 on 2023-09-05 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("content_marketing", "0018_alter_courseoverviewitem_link_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppLandingFeatureItem",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("icon", models.ImageField(blank=True, null=True, upload_to="app_landing_feature_item")),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="AppLandingFeatureModule",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "features_title",
                    models.CharField(
                        blank=True, help_text="The heading for the features section", max_length=255, null=True
                    ),
                ),
                (
                    "features_description",
                    models.TextField(
                        blank=True,
                        help_text="The description for the features section. For single feature add feature plugin",
                        null=True,
                    ),
                ),
                ("features_phone_image", models.ImageField(blank=True, null=True, upload_to="app_features")),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="AppLandingHeroModule",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("titel", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("hero_mockup_image_1", models.ImageField(blank=True, null=True, upload_to="app_landing")),
                ("hero_mockup_image_2", models.ImageField(blank=True, null=True, upload_to="app_landing")),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
    ]
