# Generated by Django 4.1.9 on 2023-09-05 08:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content_marketing", "0019_applandingfeatureitem_applandingfeaturemodule_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="applandingheromodule",
            old_name="titel",
            new_name="title",
        ),
    ]
