# Generated by Django 4.1.9 on 2023-09-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_marketing", "0022_applandingfaqitem_applandingfaqmodule"),
    ]

    operations = [
        migrations.AddField(
            model_name="applandingheromodule",
            name="apple_app_store_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="applandingheromodule",
            name="play_store_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
