# Generated by Django 4.1.9 on 2023-09-16 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
        ("content_marketing", "0024_applandingtestimonialsitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageHeroModule",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("sub_1", models.CharField(max_length=255)),
                ("sub_2", models.CharField(max_length=255)),
                ("sub_3", models.CharField(max_length=255)),
                ("link", models.CharField(blank=True, max_length=255, null=True)),
                ("link_text", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
    ]
